services:
  unicorn-backend1:
    image: ghcr.io/generalmagicio/unicorn-be:main
    container_name: unicorn-backend1
    restart: always
    ports:
      - 3000
    env_file:
      - .env
    networks:
      - unicorn-backend

  unicorn-backend2:
    image: ghcr.io/generalmagicio/unicorn-be:main
    container_name: unicorn-backend2
    restart: always
    ports:
      - 3000
    env_file:
      - .env
    networks:
      - unicorn-backend

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    networks:
      - unicorn-backend
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    environment:
      - BACKEND_URL=${BACKEND_URL:-}
      - IP_WHITELIST=${IP_WHITELIST:-0.0.0.0/0}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  caddy_config:
  caddy_data:

networks:
  unicorn-backend: